//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.CoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Registration", ReplyAction="http://tempuri.org/IUserService/RegistrationResponse")]
        string Registration(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Registration", ReplyAction="http://tempuri.org/IUserService/RegistrationResponse")]
        System.Threading.Tasks.Task<string> RegistrationAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Logout", ReplyAction="http://tempuri.org/IUserService/LogoutResponse")]
        bool Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Logout", ReplyAction="http://tempuri.org/IUserService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : DatabaseManager.CoreService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<DatabaseManager.CoreService.IUserService>, DatabaseManager.CoreService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Registration(string username, string password) {
            return base.Channel.Registration(username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegistrationAsync(string username, string password) {
            return base.Channel.RegistrationAsync(username, password);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Logout(string token) {
            return base.Channel.Logout(token);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(string token) {
            return base.Channel.LogoutAsync(token);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.ITagService")]
    public interface ITagService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/checkOutputTagExistance", ReplyAction="http://tempuri.org/ITagService/checkOutputTagExistanceResponse")]
        bool checkOutputTagExistance(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/checkOutputTagExistance", ReplyAction="http://tempuri.org/ITagService/checkOutputTagExistanceResponse")]
        System.Threading.Tasks.Task<bool> checkOutputTagExistanceAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddAnalogInput", ReplyAction="http://tempuri.org/ITagService/AddAnalogInputResponse")]
        void AddAnalogInput(Core.Model.Tag.AnalogInput analogInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddAnalogInput", ReplyAction="http://tempuri.org/ITagService/AddAnalogInputResponse")]
        System.Threading.Tasks.Task AddAnalogInputAsync(Core.Model.Tag.AnalogInput analogInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DeleteTag", ReplyAction="http://tempuri.org/ITagService/DeleteTagResponse")]
        bool DeleteTag(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DeleteTag", ReplyAction="http://tempuri.org/ITagService/DeleteTagResponse")]
        System.Threading.Tasks.Task<bool> DeleteTagAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/ToggleTagScan", ReplyAction="http://tempuri.org/ITagService/ToggleTagScanResponse")]
        void ToggleTagScan(string id, bool isOn, bool isAnalog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/ToggleTagScan", ReplyAction="http://tempuri.org/ITagService/ToggleTagScanResponse")]
        System.Threading.Tasks.Task ToggleTagScanAsync(string id, bool isOn, bool isAnalog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAnalogInput", ReplyAction="http://tempuri.org/ITagService/GetAnalogInputResponse")]
        Core.Model.Tag.AnalogInput GetAnalogInput(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAnalogInput", ReplyAction="http://tempuri.org/ITagService/GetAnalogInputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput> GetAnalogInputAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateAnalogInput", ReplyAction="http://tempuri.org/ITagService/UpdateAnalogInputResponse")]
        Core.Model.Tag.AnalogInput UpdateAnalogInput(Core.Model.Tag.AnalogInput analogInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateAnalogInput", ReplyAction="http://tempuri.org/ITagService/UpdateAnalogInputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput> UpdateAnalogInputAsync(Core.Model.Tag.AnalogInput analogInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllAnalogInputs", ReplyAction="http://tempuri.org/ITagService/GetAllAnalogInputsResponse")]
        Core.Model.Tag.AnalogInput[] GetAllAnalogInputs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllAnalogInputs", ReplyAction="http://tempuri.org/ITagService/GetAllAnalogInputsResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput[]> GetAllAnalogInputsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddAnalogOutput", ReplyAction="http://tempuri.org/ITagService/AddAnalogOutputResponse")]
        void AddAnalogOutput(Core.Model.Tag.AnalogOutput analogOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddAnalogOutput", ReplyAction="http://tempuri.org/ITagService/AddAnalogOutputResponse")]
        System.Threading.Tasks.Task AddAnalogOutputAsync(Core.Model.Tag.AnalogOutput analogOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAnalogOutput", ReplyAction="http://tempuri.org/ITagService/GetAnalogOutputResponse")]
        Core.Model.Tag.AnalogOutput GetAnalogOutput(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAnalogOutput", ReplyAction="http://tempuri.org/ITagService/GetAnalogOutputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput> GetAnalogOutputAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateAnalogOutput", ReplyAction="http://tempuri.org/ITagService/UpdateAnalogOutputResponse")]
        Core.Model.Tag.AnalogOutput UpdateAnalogOutput(Core.Model.Tag.AnalogOutput analogOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateAnalogOutput", ReplyAction="http://tempuri.org/ITagService/UpdateAnalogOutputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput> UpdateAnalogOutputAsync(Core.Model.Tag.AnalogOutput analogOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllAnalogOutputs", ReplyAction="http://tempuri.org/ITagService/GetAllAnalogOutputsResponse")]
        Core.Model.Tag.AnalogOutput[] GetAllAnalogOutputs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllAnalogOutputs", ReplyAction="http://tempuri.org/ITagService/GetAllAnalogOutputsResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput[]> GetAllAnalogOutputsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddDigitalInput", ReplyAction="http://tempuri.org/ITagService/AddDigitalInputResponse")]
        void AddDigitalInput(Core.Model.Tag.DigitalInput digitalInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddDigitalInput", ReplyAction="http://tempuri.org/ITagService/AddDigitalInputResponse")]
        System.Threading.Tasks.Task AddDigitalInputAsync(Core.Model.Tag.DigitalInput digitalInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetDigitalInput", ReplyAction="http://tempuri.org/ITagService/GetDigitalInputResponse")]
        Core.Model.Tag.DigitalInput GetDigitalInput(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetDigitalInput", ReplyAction="http://tempuri.org/ITagService/GetDigitalInputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput> GetDigitalInputAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateDigitalInput", ReplyAction="http://tempuri.org/ITagService/UpdateDigitalInputResponse")]
        Core.Model.Tag.DigitalInput UpdateDigitalInput(Core.Model.Tag.DigitalInput digitalInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateDigitalInput", ReplyAction="http://tempuri.org/ITagService/UpdateDigitalInputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput> UpdateDigitalInputAsync(Core.Model.Tag.DigitalInput digitalInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllDigitalInputs", ReplyAction="http://tempuri.org/ITagService/GetAllDigitalInputsResponse")]
        Core.Model.Tag.DigitalInput[] GetAllDigitalInputs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllDigitalInputs", ReplyAction="http://tempuri.org/ITagService/GetAllDigitalInputsResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput[]> GetAllDigitalInputsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddDigitalOutput", ReplyAction="http://tempuri.org/ITagService/AddDigitalOutputResponse")]
        void AddDigitalOutput(Core.Model.Tag.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddDigitalOutput", ReplyAction="http://tempuri.org/ITagService/AddDigitalOutputResponse")]
        System.Threading.Tasks.Task AddDigitalOutputAsync(Core.Model.Tag.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetDigitalOutput", ReplyAction="http://tempuri.org/ITagService/GetDigitalOutputResponse")]
        Core.Model.Tag.DigitalOutput GetDigitalOutput(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetDigitalOutput", ReplyAction="http://tempuri.org/ITagService/GetDigitalOutputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput> GetDigitalOutputAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateDigitalOutput", ReplyAction="http://tempuri.org/ITagService/UpdateDigitalOutputResponse")]
        Core.Model.Tag.DigitalOutput UpdateDigitalOutput(Core.Model.Tag.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/UpdateDigitalOutput", ReplyAction="http://tempuri.org/ITagService/UpdateDigitalOutputResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput> UpdateDigitalOutputAsync(Core.Model.Tag.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllDigitalOutputs", ReplyAction="http://tempuri.org/ITagService/GetAllDigitalOutputsResponse")]
        Core.Model.Tag.DigitalOutput[] GetAllDigitalOutputs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllDigitalOutputs", ReplyAction="http://tempuri.org/ITagService/GetAllDigitalOutputsResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput[]> GetAllDigitalOutputsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagServiceChannel : DatabaseManager.CoreService.ITagService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TagServiceClient : System.ServiceModel.ClientBase<DatabaseManager.CoreService.ITagService>, DatabaseManager.CoreService.ITagService {
        
        public TagServiceClient() {
        }
        
        public TagServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TagServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkOutputTagExistance(string input) {
            return base.Channel.checkOutputTagExistance(input);
        }
        
        public System.Threading.Tasks.Task<bool> checkOutputTagExistanceAsync(string input) {
            return base.Channel.checkOutputTagExistanceAsync(input);
        }
        
        public void AddAnalogInput(Core.Model.Tag.AnalogInput analogInput) {
            base.Channel.AddAnalogInput(analogInput);
        }
        
        public System.Threading.Tasks.Task AddAnalogInputAsync(Core.Model.Tag.AnalogInput analogInput) {
            return base.Channel.AddAnalogInputAsync(analogInput);
        }
        
        public bool DeleteTag(string id) {
            return base.Channel.DeleteTag(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTagAsync(string id) {
            return base.Channel.DeleteTagAsync(id);
        }
        
        public void ToggleTagScan(string id, bool isOn, bool isAnalog) {
            base.Channel.ToggleTagScan(id, isOn, isAnalog);
        }
        
        public System.Threading.Tasks.Task ToggleTagScanAsync(string id, bool isOn, bool isAnalog) {
            return base.Channel.ToggleTagScanAsync(id, isOn, isAnalog);
        }
        
        public Core.Model.Tag.AnalogInput GetAnalogInput(string id) {
            return base.Channel.GetAnalogInput(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput> GetAnalogInputAsync(string id) {
            return base.Channel.GetAnalogInputAsync(id);
        }
        
        public Core.Model.Tag.AnalogInput UpdateAnalogInput(Core.Model.Tag.AnalogInput analogInput) {
            return base.Channel.UpdateAnalogInput(analogInput);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput> UpdateAnalogInputAsync(Core.Model.Tag.AnalogInput analogInput) {
            return base.Channel.UpdateAnalogInputAsync(analogInput);
        }
        
        public Core.Model.Tag.AnalogInput[] GetAllAnalogInputs() {
            return base.Channel.GetAllAnalogInputs();
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogInput[]> GetAllAnalogInputsAsync() {
            return base.Channel.GetAllAnalogInputsAsync();
        }
        
        public void AddAnalogOutput(Core.Model.Tag.AnalogOutput analogOutput) {
            base.Channel.AddAnalogOutput(analogOutput);
        }
        
        public System.Threading.Tasks.Task AddAnalogOutputAsync(Core.Model.Tag.AnalogOutput analogOutput) {
            return base.Channel.AddAnalogOutputAsync(analogOutput);
        }
        
        public Core.Model.Tag.AnalogOutput GetAnalogOutput(string id) {
            return base.Channel.GetAnalogOutput(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput> GetAnalogOutputAsync(string id) {
            return base.Channel.GetAnalogOutputAsync(id);
        }
        
        public Core.Model.Tag.AnalogOutput UpdateAnalogOutput(Core.Model.Tag.AnalogOutput analogOutput) {
            return base.Channel.UpdateAnalogOutput(analogOutput);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput> UpdateAnalogOutputAsync(Core.Model.Tag.AnalogOutput analogOutput) {
            return base.Channel.UpdateAnalogOutputAsync(analogOutput);
        }
        
        public Core.Model.Tag.AnalogOutput[] GetAllAnalogOutputs() {
            return base.Channel.GetAllAnalogOutputs();
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.AnalogOutput[]> GetAllAnalogOutputsAsync() {
            return base.Channel.GetAllAnalogOutputsAsync();
        }
        
        public void AddDigitalInput(Core.Model.Tag.DigitalInput digitalInput) {
            base.Channel.AddDigitalInput(digitalInput);
        }
        
        public System.Threading.Tasks.Task AddDigitalInputAsync(Core.Model.Tag.DigitalInput digitalInput) {
            return base.Channel.AddDigitalInputAsync(digitalInput);
        }
        
        public Core.Model.Tag.DigitalInput GetDigitalInput(string id) {
            return base.Channel.GetDigitalInput(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput> GetDigitalInputAsync(string id) {
            return base.Channel.GetDigitalInputAsync(id);
        }
        
        public Core.Model.Tag.DigitalInput UpdateDigitalInput(Core.Model.Tag.DigitalInput digitalInput) {
            return base.Channel.UpdateDigitalInput(digitalInput);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput> UpdateDigitalInputAsync(Core.Model.Tag.DigitalInput digitalInput) {
            return base.Channel.UpdateDigitalInputAsync(digitalInput);
        }
        
        public Core.Model.Tag.DigitalInput[] GetAllDigitalInputs() {
            return base.Channel.GetAllDigitalInputs();
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalInput[]> GetAllDigitalInputsAsync() {
            return base.Channel.GetAllDigitalInputsAsync();
        }
        
        public void AddDigitalOutput(Core.Model.Tag.DigitalOutput digitalOutput) {
            base.Channel.AddDigitalOutput(digitalOutput);
        }
        
        public System.Threading.Tasks.Task AddDigitalOutputAsync(Core.Model.Tag.DigitalOutput digitalOutput) {
            return base.Channel.AddDigitalOutputAsync(digitalOutput);
        }
        
        public Core.Model.Tag.DigitalOutput GetDigitalOutput(string id) {
            return base.Channel.GetDigitalOutput(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput> GetDigitalOutputAsync(string id) {
            return base.Channel.GetDigitalOutputAsync(id);
        }
        
        public Core.Model.Tag.DigitalOutput UpdateDigitalOutput(Core.Model.Tag.DigitalOutput digitalOutput) {
            return base.Channel.UpdateDigitalOutput(digitalOutput);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput> UpdateDigitalOutputAsync(Core.Model.Tag.DigitalOutput digitalOutput) {
            return base.Channel.UpdateDigitalOutputAsync(digitalOutput);
        }
        
        public Core.Model.Tag.DigitalOutput[] GetAllDigitalOutputs() {
            return base.Channel.GetAllDigitalOutputs();
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.DigitalOutput[]> GetAllDigitalOutputsAsync() {
            return base.Channel.GetAllDigitalOutputsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.ITagValueService")]
    public interface ITagValueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/GetOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/GetOutputsValueResponse")]
        Core.Model.Tag.OutputsValue GetOutputsValue(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/GetOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/GetOutputsValueResponse")]
        System.Threading.Tasks.Task<Core.Model.Tag.OutputsValue> GetOutputsValueAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/GetLatestTagOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/GetLatestTagOutputsValueResponse")]
        double GetLatestTagOutputsValue(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/GetLatestTagOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/GetLatestTagOutputsValueResponse")]
        System.Threading.Tasks.Task<double> GetLatestTagOutputsValueAsync(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/AddOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/AddOutputsValueResponse")]
        void AddOutputsValue(Core.Model.Tag.OutputsValue outputsValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagValueService/AddOutputsValue", ReplyAction="http://tempuri.org/ITagValueService/AddOutputsValueResponse")]
        System.Threading.Tasks.Task AddOutputsValueAsync(Core.Model.Tag.OutputsValue outputsValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagValueServiceChannel : DatabaseManager.CoreService.ITagValueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TagValueServiceClient : System.ServiceModel.ClientBase<DatabaseManager.CoreService.ITagValueService>, DatabaseManager.CoreService.ITagValueService {
        
        public TagValueServiceClient() {
        }
        
        public TagValueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TagValueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagValueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagValueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Core.Model.Tag.OutputsValue GetOutputsValue(int id) {
            return base.Channel.GetOutputsValue(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.Tag.OutputsValue> GetOutputsValueAsync(int id) {
            return base.Channel.GetOutputsValueAsync(id);
        }
        
        public double GetLatestTagOutputsValue(string tagName) {
            return base.Channel.GetLatestTagOutputsValue(tagName);
        }
        
        public System.Threading.Tasks.Task<double> GetLatestTagOutputsValueAsync(string tagName) {
            return base.Channel.GetLatestTagOutputsValueAsync(tagName);
        }
        
        public void AddOutputsValue(Core.Model.Tag.OutputsValue outputsValue) {
            base.Channel.AddOutputsValue(outputsValue);
        }
        
        public System.Threading.Tasks.Task AddOutputsValueAsync(Core.Model.Tag.OutputsValue outputsValue) {
            return base.Channel.AddOutputsValueAsync(outputsValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.IAlarmService", CallbackContract=typeof(DatabaseManager.CoreService.IAlarmServiceCallback))]
    public interface IAlarmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/AddAlarm", ReplyAction="http://tempuri.org/IAlarmService/AddAlarmResponse")]
        void AddAlarm(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/AddAlarm", ReplyAction="http://tempuri.org/IAlarmService/AddAlarmResponse")]
        System.Threading.Tasks.Task AddAlarmAsync(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/RemoveAlarm", ReplyAction="http://tempuri.org/IAlarmService/RemoveAlarmResponse")]
        void RemoveAlarm(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/RemoveAlarm", ReplyAction="http://tempuri.org/IAlarmService/RemoveAlarmResponse")]
        System.Threading.Tasks.Task RemoveAlarmAsync(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmById", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmByIdResponse")]
        Core.Model.AlarmTrigger GetAlarmById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmById", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmByIdResponse")]
        System.Threading.Tasks.Task<Core.Model.AlarmTrigger> GetAlarmByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAllAlarms", ReplyAction="http://tempuri.org/IAlarmService/GetAllAlarmsResponse")]
        Core.Model.AlarmTrigger[] GetAllAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAllAlarms", ReplyAction="http://tempuri.org/IAlarmService/GetAllAlarmsResponse")]
        System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAllAlarmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/LogAlarm", ReplyAction="http://tempuri.org/IAlarmService/LogAlarmResponse")]
        void LogAlarm(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/LogAlarm", ReplyAction="http://tempuri.org/IAlarmService/LogAlarmResponse")]
        System.Threading.Tasks.Task LogAlarmAsync(Core.Model.AlarmTrigger alarm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmsInPeriod", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmsInPeriodResponse")]
        Core.Model.AlarmTrigger[] GetAlarmsInPeriod(System.DateTime startTime, System.DateTime endTime, bool sortOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmsInPeriod", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmsInPeriodResponse")]
        System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAlarmsInPeriodAsync(System.DateTime startTime, System.DateTime endTime, bool sortOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmsByPriority", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmsByPriorityResponse")]
        Core.Model.AlarmTrigger[] GetAlarmsByPriority(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/GetAlarmsByPriority", ReplyAction="http://tempuri.org/IAlarmService/GetAlarmsByPriorityResponse")]
        System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAlarmsByPriorityAsync(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/SubscribeToAlarmDisplay", ReplyAction="http://tempuri.org/IAlarmService/SubscribeToAlarmDisplayResponse")]
        void SubscribeToAlarmDisplay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/SubscribeToAlarmDisplay", ReplyAction="http://tempuri.org/IAlarmService/SubscribeToAlarmDisplayResponse")]
        System.Threading.Tasks.Task SubscribeToAlarmDisplayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarmService/AlarmTriggered")]
        void AlarmTriggered(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmServiceChannel : DatabaseManager.CoreService.IAlarmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmServiceClient : System.ServiceModel.DuplexClientBase<DatabaseManager.CoreService.IAlarmService>, DatabaseManager.CoreService.IAlarmService {
        
        public AlarmServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AlarmServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AlarmServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddAlarm(Core.Model.AlarmTrigger alarm) {
            base.Channel.AddAlarm(alarm);
        }
        
        public System.Threading.Tasks.Task AddAlarmAsync(Core.Model.AlarmTrigger alarm) {
            return base.Channel.AddAlarmAsync(alarm);
        }
        
        public void RemoveAlarm(Core.Model.AlarmTrigger alarm) {
            base.Channel.RemoveAlarm(alarm);
        }
        
        public System.Threading.Tasks.Task RemoveAlarmAsync(Core.Model.AlarmTrigger alarm) {
            return base.Channel.RemoveAlarmAsync(alarm);
        }
        
        public Core.Model.AlarmTrigger GetAlarmById(int id) {
            return base.Channel.GetAlarmById(id);
        }
        
        public System.Threading.Tasks.Task<Core.Model.AlarmTrigger> GetAlarmByIdAsync(int id) {
            return base.Channel.GetAlarmByIdAsync(id);
        }
        
        public Core.Model.AlarmTrigger[] GetAllAlarms() {
            return base.Channel.GetAllAlarms();
        }
        
        public System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAllAlarmsAsync() {
            return base.Channel.GetAllAlarmsAsync();
        }
        
        public void LogAlarm(Core.Model.AlarmTrigger alarm) {
            base.Channel.LogAlarm(alarm);
        }
        
        public System.Threading.Tasks.Task LogAlarmAsync(Core.Model.AlarmTrigger alarm) {
            return base.Channel.LogAlarmAsync(alarm);
        }
        
        public Core.Model.AlarmTrigger[] GetAlarmsInPeriod(System.DateTime startTime, System.DateTime endTime, bool sortOption) {
            return base.Channel.GetAlarmsInPeriod(startTime, endTime, sortOption);
        }
        
        public System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAlarmsInPeriodAsync(System.DateTime startTime, System.DateTime endTime, bool sortOption) {
            return base.Channel.GetAlarmsInPeriodAsync(startTime, endTime, sortOption);
        }
        
        public Core.Model.AlarmTrigger[] GetAlarmsByPriority(int priority) {
            return base.Channel.GetAlarmsByPriority(priority);
        }
        
        public System.Threading.Tasks.Task<Core.Model.AlarmTrigger[]> GetAlarmsByPriorityAsync(int priority) {
            return base.Channel.GetAlarmsByPriorityAsync(priority);
        }
        
        public void SubscribeToAlarmDisplay() {
            base.Channel.SubscribeToAlarmDisplay();
        }
        
        public System.Threading.Tasks.Task SubscribeToAlarmDisplayAsync() {
            return base.Channel.SubscribeToAlarmDisplayAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.ITrendingService", CallbackContract=typeof(DatabaseManager.CoreService.ITrendingServiceCallback))]
    public interface ITrendingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrendingService/SubscribeToTrending", ReplyAction="http://tempuri.org/ITrendingService/SubscribeToTrendingResponse")]
        void SubscribeToTrending();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrendingService/SubscribeToTrending", ReplyAction="http://tempuri.org/ITrendingService/SubscribeToTrendingResponse")]
        System.Threading.Tasks.Task SubscribeToTrendingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrendingService/initTagTable")]
        void initTagTable(System.Collections.Generic.Dictionary<string, double> tags);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrendingService/addTagValue")]
        void addTagValue(string tagName, double value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrendingService/removeTag")]
        void removeTag(string tagName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingServiceChannel : DatabaseManager.CoreService.ITrendingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingServiceClient : System.ServiceModel.DuplexClientBase<DatabaseManager.CoreService.ITrendingService>, DatabaseManager.CoreService.ITrendingService {
        
        public TrendingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TrendingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TrendingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeToTrending() {
            base.Channel.SubscribeToTrending();
        }
        
        public System.Threading.Tasks.Task SubscribeToTrendingAsync() {
            return base.Channel.SubscribeToTrendingAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreService.IRealTimeDriver")]
    public interface IRealTimeDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriver/SendMessageResponse")]
        void SendMessage(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriver/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SubscribeRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeDriver/SubscribeRealTimeUnitResponse")]
        void SubscribeRealTimeUnit(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SubscribeRealTimeUnit", ReplyAction="http://tempuri.org/IRealTimeDriver/SubscribeRealTimeUnitResponse")]
        System.Threading.Tasks.Task SubscribeRealTimeUnitAsync(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/GetRealTimeUnitValue", ReplyAction="http://tempuri.org/IRealTimeDriver/GetRealTimeUnitValueResponse")]
        double GetRealTimeUnitValue(string IOAdress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/GetRealTimeUnitValue", ReplyAction="http://tempuri.org/IRealTimeDriver/GetRealTimeUnitValueResponse")]
        System.Threading.Tasks.Task<double> GetRealTimeUnitValueAsync(string IOAdress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverChannel : DatabaseManager.CoreService.IRealTimeDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverClient : System.ServiceModel.ClientBase<DatabaseManager.CoreService.IRealTimeDriver>, DatabaseManager.CoreService.IRealTimeDriver {
        
        public RealTimeDriverClient() {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(string message, byte[] signature) {
            base.Channel.SendMessage(message, signature);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message, byte[] signature) {
            return base.Channel.SendMessageAsync(message, signature);
        }
        
        public void SubscribeRealTimeUnit(string message, byte[] signature) {
            base.Channel.SubscribeRealTimeUnit(message, signature);
        }
        
        public System.Threading.Tasks.Task SubscribeRealTimeUnitAsync(string message, byte[] signature) {
            return base.Channel.SubscribeRealTimeUnitAsync(message, signature);
        }
        
        public double GetRealTimeUnitValue(string IOAdress) {
            return base.Channel.GetRealTimeUnitValue(IOAdress);
        }
        
        public System.Threading.Tasks.Task<double> GetRealTimeUnitValueAsync(string IOAdress) {
            return base.Channel.GetRealTimeUnitValueAsync(IOAdress);
        }
    }
}
